spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/db_aerolineas
    username: root
  application:
    name: VuelosApplication
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
